version: '3.7'

services:
  calendar_api:
    image: calendar_api:latest
    container_name: calendar_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONF_PATH: "/app/conf.yml"
    ports:
      - "8888:80"
    volumes:
      - "./conf.yml:/app/conf.yml"
    networks:
      calendar-net:

networks:
  calendar-net:
    name: calendar-net

