version: '3.7'

services:
  calendar_pg:
    image: postgres:11
    container_name: calendar_pg
    environment:
      POSTGRES_PASSWORD: 12345
    expose:
      - "5432"
    networks:
      calendar-net:

  calendar_pg_migration:
    image: migrate/migrate:latest
    container_name: calendar_pg_migration
    entrypoint:
      - "sh"
      - "-c"
      - "`while ! /migrate -path /migrations -database postgres://postgres:12345@calendar_pg:5432/postgres?sslmode=disable up; do sleep 2; done;`"
    volumes:
      - "./api/migrations:/migrations"
    networks:
      calendar-net:

  calendar_rmq:
    image: rabbitmq:management-alpine
    container_name: calendar_rmq
    ports:
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    volumes:
      - ./rmq_plugins.txt:/etc/rabbitmq/enabled_plugins
    networks:
      calendar-net:

  calendar_prom:
    image: prom/prometheus:latest
    container_name: calendar_prom
    command:
      - '--config.file=/etc/prometheus/conf.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=2d'
    ports:
      - "7744:9090"
    volumes:
      - ./prom_conf.yml:/etc/prometheus/conf.yml
    networks:
      calendar-net:

  calendar_pg_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: calendar_pg_exporter
    environment:
      PG_EXPORTER_WEB_LISTEN_ADDRESS: :9393
      DATA_SOURCE_NAME: postgres://postgres:12345@calendar_pg:5432/postgres?sslmode=disable
      PG_EXPORTER_DISABLE_SETTINGS_METRICS: "true"
      PG_EXPORTER_EXTEND_QUERY_PATH: /pr_query.yml
    expose:
      - "9393"
    volumes:
      - ./prom_pg_query.yml:/pr_query.yml
    networks:
      calendar-net:

  calendar_api:
    image: calendar_api:latest
    container_name: calendar_api
    build: ./api
    environment:
      LOG_LEVEL: debug
      PG_DSN: postgres://postgres:12345@calendar_pg:5432/postgres?sslmode=disable
      M_HTTP_LISTEN: :9102
    expose:
      - "9102"
    ports:
      - "8888:80"
    networks:
      calendar-net:

  calendar_scheduler:
    image: calendar_scheduler:latest
    container_name: calendar_scheduler
    build: ./scheduler
    environment:
      LOG_LEVEL: debug
      PG_DSN: postgres://postgres:12345@calendar_pg:5432/postgres?sslmode=disable
      RMQ_DSN: amqp://guest:guest@calendar_rmq:5672/
    networks:
      calendar-net:

  calendar_sender:
    image: calendar_sender:latest
    container_name: calendar_sender
    build: ./sender
    environment:
      LOG_LEVEL: debug
      RMQ_DSN: amqp://guest:guest@calendar_rmq:5672/
    networks:
      calendar-net:

networks:
  calendar-net:
    name: calendar-net
